// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPedido struct {
	Name       string `json:"name"`
	Quantidade int    `json:"quantidade"`
	UsuarioID  int    `json:"usuario_id"`
}

type NewUsuario struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Pedido struct {
	ID         *int   `json:"id,omitempty"`
	Name       string `json:"name"`
	Quantidade int    `json:"quantidade"`
	UsuarioID  int    `json:"usuario_id"`
}

type Usuario struct {
	ID       *int   `json:"id,omitempty"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
